name: Heel.al
favicon: null
layout_spectrum: 0.90363
typography_spectrum: 0.50909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcdfd7'
    - '#060606'
    - '#f08456'
    - '#4d4e45'
    - '#787066'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
